services:
  mysql80:
    image: mysql:8.0
    networks:
      - my_net1
    volumes:
      - ./backend/db/conf.d:/etc/mysql/conf.d
      - ./backend/db/data:/var/lib/mysql
      - ./backend/db/initdb.d:/etc/mysql/docker-entrypoint-initdb.d
    env_file: ./backend/.env
    ports:
      - "3307:3306"
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my_net1
    ports:
      - "8080:8080"
    depends_on:
      - mysql80
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql80:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=1111
      # - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my_net1
  nginx:
    image: nginx:latest
    networks:
      - my_net1
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

networks:
  my_net1:
    driver: bridge